CREATE TABLE conns (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  headers JSONB,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'),
  closed_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE disconns (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE subs (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  nostr_sub_id TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE eoses (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  nostr_sub_id TEXT,
  eose_count INTEGER DEFAULT 0,
  eose_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE unsubs (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE filters (
  id BIGSERIAL PRIMARY KEY,
  sub_id BIGINT REFERENCES subs(id) ON DELETE CASCADE,
  since INTEGER,
  until INTEGER,
  lmt INTEGER,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE event_ids (
  id BIGSERIAL PRIMARY KEY,
  filter_id BIGINT REFERENCES filters(id) ON DELETE CASCADE,
  event_id TEXT
);

CREATE TABLE authors (
  id BIGSERIAL PRIMARY KEY,
  filter_id BIGINT REFERENCES filters(id) ON DELETE CASCADE,
  author TEXT
);

CREATE TABLE kinds (
  id BIGSERIAL PRIMARY KEY,
  filter_id BIGINT REFERENCES filters(id) ON DELETE CASCADE,
  kind INTEGER
);

CREATE TABLE tags (
  id BIGSERIAL PRIMARY KEY,
  filter_id BIGINT REFERENCES filters(id) ON DELETE CASCADE,
  tag TEXT
);

CREATE TABLE vals (
  id BIGSERIAL PRIMARY KEY,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  val TEXT
);

CREATE TABLE notices (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  msg TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE errors (
  id BIGSERIAL PRIMARY KEY,
  ip TEXT,
  msg TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);